apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-secrets-store-provider-spring-cloud-config
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-secrets-store-provider-spring-cloud-config-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-secrets-store-provider-spring-cloud-config-role
subjects:
  - kind: ServiceAccount
    name: csi-secrets-store-provider-spring-cloud-config
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-secrets-store-provider-spring-cloud-config-role
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-secrets-store-provider-spring-cloud-config
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: csi-secrets-store-provider-spring-cloud-config
  template:
    metadata:
      labels:
        app: csi-secrets-store-provider-spring-cloud-config
    spec:
      serviceAccountName: csi-secrets-store-provider-spring-cloud-config
      containers:
        - name: provider
          image: ghcr.io/freenowtech/secrets-store-csi-driver-provider-spring-cloud-config:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 5m
              memory: 25Mi
            limits:
              cpu: 5m
              memory: 25Mi
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
          env:
            - name: TARGET_DIR
              value: "/etc/kubernetes/secrets-store-csi-providers"
          volumeMounts:
            - mountPath: "/etc/kubernetes/secrets-store-csi-providers"
              name: providervol
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: HostToContainer
      volumes:
        - name: providervol
          hostPath:
            path: /etc/kubernetes/secrets-store-csi-providers
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
      nodeSelector:
        kubernetes.io/os: linux
